In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7203, 2038, 4712, 9744],
 [7203, 2038, 4712, 3225],
 [7203, 7836, 4712, 2466],
 [6300, 3352, 8960, 7667, 8344],
 [6300, 3352, 8960, 7667, 7194],
 [5159, 7203, 7016, 4712, 7146],
 [6118, 2571, 2763, 7667]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7203 2038 4712 9744]
 [   0    0    0    0 7203 2038 4712 3225]
 [   0    0    0    0 7203 7836 4712 2466]
 [   0    0    0 6300 3352 8960 7667 8344]
 [   0    0    0 6300 3352 8960 7667 7194]
 [   0    0    0 5159 7203 7016 4712 7146]
 [   0    0    0    0 6118 2571 2763 7667]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\aumpa\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step


array([[[ 0.0407101 , -0.00065695, -0.02438332, -0.04537786,
         -0.04471724,  0.00796639,  0.02346421, -0.04020883,
         -0.02311095, -0.0074769 ],
        [ 0.0407101 , -0.00065695, -0.02438332, -0.04537786,
         -0.04471724,  0.00796639,  0.02346421, -0.04020883,
         -0.02311095, -0.0074769 ],
        [ 0.0407101 , -0.00065695, -0.02438332, -0.04537786,
         -0.04471724,  0.00796639,  0.02346421, -0.04020883,
         -0.02311095, -0.0074769 ],
        [ 0.0407101 , -0.00065695, -0.02438332, -0.04537786,
         -0.04471724,  0.00796639,  0.02346421, -0.04020883,
         -0.02311095, -0.0074769 ],
        [ 0.01765139, -0.0386251 , -0.0307755 , -0.02400813,
         -0.02001634,  0.00039252,  0.01541862, -0.00214307,
         -0.04210471, -0.00012237],
        [-0.00698602,  0.04471678,  0.04671333, -0.0323555 ,
         -0.00797224,  0.03687974, -0.02664007,  0.0059212 ,
          0.02506728,  0.04613001],
        [ 0.03763186,  0.03955075, -0.01790516,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 7203, 2038, 4712, 9744])